# Generated by Django 3.2.16 on 2023-07-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sliderupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='slider/')),
            ],
        ),
    ]
