# Generated by Django 3.2.6 on 2023-07-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='formdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernamedata', models.CharField(max_length=255, null=True)),
                ('emaildata', models.CharField(max_length=255, null=True)),
                ('pickuplocation', models.CharField(max_length=255, null=True)),
                ('dropofflocation', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
