# Generated by Django 3.2.6 on 2023-07-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_formdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderupdate',
            name='heading2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
