# Generated by Django 3.2.6 on 2023-07-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sliderupdate_heading2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderupdate',
            name='image',
            field=models.ImageField(null=True, upload_to='slider/'),
        ),
    ]
