# Generated by Django 3.2.6 on 2023-07-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_sliderupdate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
    ]
