# Generated by Django 3.2.16 on 2023-07-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_sliderupdate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDatatest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field1', models.CharField(max_length=100)),
                ('text_field2', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/')),
            ],
        ),
    ]
