# Generated by Django 3.2.16 on 2023-07-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_sliderupdate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
    ]
