# Generated by Django 3.2.16 on 2023-07-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_sliderupdate_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormDatatest',
        ),
    ]
