# Generated by Django 3.2.16 on 2023-07-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_delete_formdatatest'),
    ]

    operations = [
        migrations.CreateModel(
            name='onewaybooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('user_email', models.CharField(max_length=255, null=True)),
                ('pickuplocation', models.CharField(max_length=255, null=True)),
                ('dropofflocation', models.CharField(max_length=255, null=True)),
                ('pickup_date', models.IntegerField(null=True)),
            ],
        ),
    ]
