# Generated by Django 3.2.16 on 2023-07-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_onewaybooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onewaybooking',
            name='pickup_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
