# Generated by Django 3.2.6 on 2023-07-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20230728_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255, null=True)),
                ('seating_capacity', models.IntegerField(null=True)),
                ('rate_par_km', models.IntegerField(null=True)),
                ('min_range', models.IntegerField(null=True)),
                ('driver_allowance', models.IntegerField(null=True)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='carImage/')),
            ],
        ),
    ]
