# Generated by Django 3.2.16 on 2023-07-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_start', models.CharField(max_length=255, null=True)),
                ('ride_end', models.CharField(max_length=255, null=True)),
                ('ride_type', models.CharField(max_length=255, null=True)),
                ('sedan_price', models.IntegerField(null=True)),
                ('suv_price', models.IntegerField(null=True)),
            ],
        ),
    ]
