# Generated by Django 3.2.16 on 2023-07-31 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_aboutus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aboutus',
            new_name='about',
        ),
    ]
