# Generated by Django 3.2.16 on 2023-07-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_rename_aboutus_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='mission',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='vision',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
