# Generated by Django 3.2.16 on 2023-08-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20230731_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_Address', models.CharField(max_length=255, null=True)),
                ('contact_Email', models.EmailField(max_length=255, null=True)),
                ('contact_Mobile', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gallery_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('gallery_image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='services_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_Name', models.CharField(max_length=255, null=True)),
                ('service_Description', models.CharField(max_length=1000, null=True)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service/')),
            ],
        ),
    ]
