# Generated by Django 3.2.6 on 2023-08-01 18:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_contactus_gallery_data_services_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_desc1',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True),
        ),
    ]
