# Generated by Django 3.2.6 on 2023-08-01 19:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_about_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_title',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True),
        ),
    ]
