# Generated by Django 3.2.16 on 2023-08-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_about_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=255, null=True)),
                ('contactEmail', models.EmailField(max_length=254, null=True)),
                ('contactPhone', models.IntegerField(null=True)),
                ('contactSubject', models.CharField(max_length=500, null=True)),
                ('contactMessage', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='about_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
